repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 25.12.0
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py38
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: 7.3.0
    hooks:
      - id: flake8-conda
        args: ["--max-line-length=88"]
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: 7.0.0
    hooks:
      - id: isort-conda
        additional_dependencies: [-c, conda-forge, toml=0.10.2]
  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: "1.19.0"
    hooks:
      - id: mypy-conda
        additional_dependencies: [-c, conda-forge, types-setuptools]
  - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
    rev: 3.21.2
    hooks:
      - id: pyupgrade-conda
        args:
          - --py38-plus
  - repo: https://github.com/Quantco/pre-commit-mirrors-prettier
    rev: 3.7.4
    hooks:
      - id: prettier-conda
        files: "\\.md$"
  - repo: https://github.com/Quantco/pre-commit-mirrors-pre-commit-hooks
    rev: 5.0.0
    hooks:
      - id: trailing-whitespace-conda
      - id: end-of-file-fixer-conda
